from cravat import BaseConverter
from cravat import BadFormatError
import cravat.constants as constants
from pyliftover import LiftOver
import os
from cravat.exceptions import LiftoverFailure, InvalidData
from cravat.inout import CravatWriter
from cravat import get_wgs_reader

class CravatConverter(BaseConverter):
    
    def __init__(self):
        self.format_name = '23andme'
        self.addl_cols = [
            {
                'name':'zygosity',
                'title':'Zygosity',
                'type':'string'
            },
        ]
        self.found_vars = set()
    
    def check_format(self, f):
        for l in f:
            if l.startswith('#'):
                if 'generated by 23andMe'.lower() in l.lower():
                    return True
            else:
                break
        return False
    
    def setup(self, f):
        # read ref bases from the input's own assembly. There is no hg18wgs,
        # so hg18 positions are lifted to hg38 just to look up the ref.
        self.lifter = None
        if self.input_assembly == 'hg38':
            self.wgs = get_wgs_reader(assembly='hg38')
        elif self.input_assembly == 'hg18':
            self.wgs = get_wgs_reader(assembly='hg38')
            self.lifter = LiftOver(constants.liftover_chain_paths['hg18'])
        else:
            self.wgs = get_wgs_reader(assembly='hg19')
        self.good_vars = set(['T','C','G','A'])

    def get_ref(self, chrom, pos):
        if self.lifter is None:
            return self.wgs.slice(chrom, pos).upper()
        res = self.lifter.convert_coordinate(chrom, pos - 1)
        if not res or len(res) > 1:
            raise InvalidData(f'Unable to find hg18 ref for {chrom}:{pos}')
        newchrom, newpos, strand = res[0][0], res[0][1] + 1, res[0][2]
        ref = self.wgs.slice(newchrom, newpos).upper()
        if strand == '-':
            ref = self.complement.get(ref, ref)
        return ref

    complement = {'A':'T', 'C':'G', 'G':'C', 'T':'A'}

    def convert_line(self, l):
        ret = []
        if l.startswith('#'): return self.IGNORE
        toks = l.strip('\r\n').split('\t')
        tags = toks[0]
        chrom = toks[1]
        if chrom=='MT':
            chrom = 'M'
        chrom = 'chr'+chrom
        pos = int(toks[2])
        try:
            ref = self.get_ref(chrom, pos)
        except KeyError:
            raise InvalidData(f'Bad chrom {chrom}')
        except IndexError:
            raise InvalidData(f'Bad position {pos}')
        sample = ''
        geno = toks[3]
        zygosity = None
        try:
            if geno[0]==geno[1]:
                zygosity = 'hom'
            else:
                zygosity = 'het'
        except IndexError:
            zygosity = 'hom'
            
        for var in geno:
            if var in self.good_vars and var != ref:
                alt = var
                unq_var = (chrom, pos, ref, alt)
                if unq_var in self.found_vars:
                    continue
                else:
                    self.found_vars.add(unq_var)
                wdict = {
                    'tags':tags,
                    'chrom':chrom,
                    'pos':pos,
                    'ref_base':ref,
                    'alt_base':alt,
                    'sample_id':sample,
                    'zygosity':zygosity,
                }
                ret.append(wdict)
        if not ret:
            return self.IGNORE
        if zygosity == 'hom':
            ret = ret[:1]
        return ret
