title: Base Package
version: 0.0.1
type: package
developer:
  name: OpenCRAVAT Team
  organization: KarchinLab
  email: support@opencravat.org
  website: https://opencravat.org
  citation: ''
description: Base OpenCRAVAT modules. Needed for each install.
private: true
requires:
- hg38
- cravat-converter
- vcf-converter
- oldcravat-converter
- textreporter
- excelreporter
- tagsampler
- vcfinfo
- wgbase
- wgncrna
- wglollipop
- wgndex
- wgcircossummary
- wgcodingvsnoncodingsummary
- wggosummary
- wgsosamplesummary
- wgsosummary
- wgtopgenessummary
