title: Clingen Allele Registry Converter
version: 1.0.0
type: converter
description: File converter for Clingen Allele Registry Canonical Allele Identifiers
api_url: https://reg.clinicalgenome.org/alleles?file=id
batch_size: 10000
developer:
  name: Kyle Anderson
  organization: Potomac IT Group
  email: kanderson@potomacitgroup.com
  website: https://potomacitgroup.com/
  citation: ''
requires_opencravat: '>=1.8.0'
release_note:
  1.0.0: Initial release of Clingen Allele Registry input
