title: HGVS Converter
version: 1.1.0
type: converter
description: File converter for HGVS string input
api_url: https://hgvs.opencravat.org
batch_size: 1000
developer:
  name: Kyle Anderson
  organization: Potomac IT Group
  email: kanderson@potomacitgroup.com
  website: https://potomacitgroup.com/
  citation: ''
requires_opencravat: '>=1.8.0'
release_note:
  1.1.0: Change to use local cdot data provider files, add batch query
  1.0.0: Initial release of HGVS input
